server:
  #配置端口号
  port: 8082

spring:
  #配置RabbitMQ
  rabbitmq:
    #端口号
    host: 192.168.75.130
    #用户名
    username: admin
    #密码
    password: 123
    #端口
    port: 5672
    template:
      mandatory: true
  #邮箱配置
  mail:
    #邮件服务器地址
    host: smtp.qq.com
    #协议
    protocol: smtps
    #编码格式
    default-encoding: utf-8
    #授权码
    password: xyutedfzaruobhjh
    #邮箱地址
    username: 1808870333@qq.com
    # 端口号
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
  #设置redis连接
  redis:
    #连接地址
    host: 192.168.75.130
    #连接端口
    port: 6379
    #超时时间
    timeout: 10000ms
    #数据库索引
    database: 0
    #连接属性
    lettuce:
      pool:
        #最大连接数
        max-active: 100
        #最小连接数
        max-idle: 5
        #最大阻塞时间
        max-wait: 5000ms
